async function main() {
  try {

    

  } catch (erro) {
    console.log(`Erro na função main no arquivo main.js
    ${erro.name}: ${erro.message}`);
  }
};

main();